### ISSUE TITLE
Use a proper file browser widget in `DataBrowser`

### ISSUE THREAD

**Issue by kuadrat** [pudeIko/piva#14]
### Current behaviour

In order to change the list of files displayed in `DataBrowser`'s `QListView` one has to open a filedialog, navigate to a different directory and close that dialog.

### Desired behaviour

This process could be streamlined by simply using some file browsing widget in place of the `QListView` in the first place.

**Comment by pudeIko** [comment]
On Mac an Windows:
The file browser has a frozen view of home directory. 
It allows for browsing down to required files, but can be annoying when they are deep in folder tree.
Also, it doesn't allow to view files in directories above the `/~`, which is not a big problem, but a small limitation.

Maybe there is a straightforward solution?

**Comment by kuadrat** [comment]
1. Horizontally frozen view: The easiest solution might be adding a horizontal scrollbar.
2. Browsing beyond `~`: I implemented this as a feature with the idea to limit the visible file system to the relevant parts. It's trivial to change this behaviour to include everything from the file system root. However, at least in linux (and likely MacOS?) it should be unlikely to be necessary to browse beyond `~`? Is it different on windows?

**Comment by kuadrat** [comment]
1. Fixed with [74ae70f](https://github.com/pudeIko/piva/commit/74ae70feda9846d36ef0e0e7187b1d5262700940)
2. One idea would be to use the currently obsolete *Open File* function (shortcut `Ctrl + O`) to instead set the displayed filesystem root. This we, we can start with a reasonable default but give users the freedom to visit their whole filesystem. Thoughts?

**Comment by pudeIko** [comment]
The problem actually appeared already. 
At the beamline, data are shared between machines via mapped drivers. On windows that means that mapped driver gets its own address (e.g. `Z:\`), and therefore cannot be accessed from `C:\Users\xxx`

Same problem will inevitably appear on Linux and Mac, where mapped directories are located in `/Volumes/xxx/`.
