### ISSUE TITLE
import data-slicer and arpys modules instead of copy pasting them

### ISSUE THREAD

**Issue by kuadrat** [pudeIko/piva#16]
Currently, many of the tools provided by `data-slicer` and `arpys` are being used in `piva` through copy-pasted source code. The proper way for doing this would be to add `data-slicer` and `piva` as a dependency and import the respective objects.
Subclassing and overriding can be used wherever adaptations to the original tools become necessary.

Doing it properly has the advantage that we automatically have all its features at our disposal and only have to build on top of them. Especially relevant is the case of the `arpys.dataloading` module, where dataloaders need to be changed frequently and all users would benefit from a single place where they know they can find the most up-to-date version - either for their use or for implementing their own updates.

**Comment by pudeIko** [comment]
Done for TracedVariable. Rest of the classes were significantly modified to make them work in piva.
