### ISSUE TITLE
Inverting colormap on macOS

### ISSUE THREAD

**Issue by kuadrat** [pudeIko/piva#30]
Apparently, this is not working in version `piva 1.0.2`.
More info would be welcome.

**Comment by jukue** [comment]
Hi, 

The error message when trying ti invert colors is: 

Traceback (most recent call last):
  File "PATH_TO_PIVA/piva/_2Dviewer.py", line 534, in set_cmap
    if self.util_panel.image_invert_colors.isChecked() and MY_CMAPS:
NameError: name 'MY_CMAPS' is not defined

Thanks.

**Comment by kuadrat** [comment]
Thanks! Turns out, this is not an OS issue at all. It's a very simple bug that just went under the radar because I kept testing with 3Dviewer, not with 2Dviewer.
@pudeIko one more reason why inheritance would be preferred to parallel implementations ;)

This will be fixed in the next version.
