### ISSUE TITLE
Parallelize k space conversion

### ISSUE THREAD

**Issue by kuadrat** [pudeIko/piva#37]
An idea that popped up in discussions with colleagues:
We could try to speed up k-space conversion by making use of the fact that nowadays pretty much every machine has multiple cores.

**Comment by pudeIko** [comment]
As far as I understand, that exactly what should be done by `numba`. It precompiles a part of code, and the compiler is taking care of making binary code running on multiple cores. 
It works especially good with `numpy.arrays`, but supports only small part of `numpy` library. For that reason, it should be used only for specific parts of the code, e.g. the ones containing time consuming `for` loops.

**Comment by kuadrat** [comment]
Wow, that seems to be what `numba` does, indeed! What a clever library!

I added the `parallel=True` option and changed the `range(...)` for loops to `prange(...)`, as described [here](https://numba.readthedocs.io/en/stable/user/parallel.html).
For me, this has resulted in another speedup by a factor of 2.

However, I have 8 cores and I wonder if there will still be any gain if this is run on a machine with fewer cores (like 2-4). In the worst case, the overhead that numba likely needs to split everything across different cores might actually cost more than one gains if there are few cores or small files.

I will test this on 4 cores next week :)

**Comment by kuadrat** [comment]
A first test already shows that "more parallel" isn't always better: I removed all `prange` except for the outermost loop.
With this, I get another 5% (small but noticeable) gain in speed.

Thus, really optimizing the routine will require some trial and error. But I personally think, what we have now is already "good enough"<sup>TM</sup>
