### ISSUE TITLE
K-space conversion for hv scans (and normal ones as well)

### ISSUE THREAD

**Issue by pudeIko** [pudeIko/piva#8]
Implementing k-space conversion (just for kz scans) by changing analyzer axis sampling.

**Comment by pudeIko** [comment]
PColorMesh class, although available in `pyqtgraph`, works incredibly slow for interactive applications. 

A possible workaround would be to rescale raw dataset (solution widely used in Igor community). 

Drawbacks: 
1) rescaling can take a while (`numba` probably could help), 
2) to not lose progress, rescaled dataset needs to be saved,
3) saved data file will be bigger, especially painful with hv scans.

All suggestions much appreciated.

**Comment by kuadrat** [comment]
The drawbacks of rescaling seem quite obvious, so I'm surprised that it's widely used with Igor. Do you have any idea of how much they rescale? Is it more a factor of 2 or a factor of 10? Naively, this would lead to 10x larger files, right?

I also gave `PColorMeshItem` a shot and have come to the same conclusion as you. Additionally, it would be difficult to extract slices from `PColorMeshItem`s.

One approach I could imagine would be to do a *discrete* k space conversion, where we only shift channels by an integer amount of pixels. (If I understand correctly, this would be kind of equivalent to the *rescaling* approach, but with a scaling factor of 1) Of course, the precision of this way would be limited to the pixel size. On the bright side, all slicing functionality would be readily available and handling data on rectangular generally is generally more convenient.

**Comment by pudeIko** [comment]
From what I checked it's a bit more than 2 in size. And I think it's a limit, because I've tested it in already quite wide hv range. 
For simple Femi surfaces I'm sure it will be <1.5.

I'm not sure what you mean by discrete conversion. To remain the size of dataset you'd lose some data, wouldn't you?
